language: go
sudo: false
branches:
  only:
  - sources
notifications:
  email:
    - halfdane@gmx.net
install:
- go get -v github.com/spf13/hugo
script: hugo
after_success:
- cd public
- grep "Eudemus" other/work_in_progress/index.html
- git init
- git config user.email "travis@example.com"
- git config user.name "Travis ci"
- git add .
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push --force --quiet "https://${PUSH_TOKEN}@github.com/DavidSedley/DavidSedley.github.io.git" master:master 2>&1 >/dev/null
