sudo: false
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/halfdane/dsedley.git
    - secure: D4Jl0u4ifWi80IMJepvbYdxH2EpA/+MC2Y1eAGwKx0GNCEk3gg5fGzrIGnnYw1I/5cAKkrGCr82qp4AOxjFmOXFEECpaBWSyaBEE4gIf/VNzCJEZ/Mwfgz6XEpTGKmW2gPNybzlBVWO2/WIK0hxRdStmrpBrfiSHYS9wHIpsxXLngpKN2ngIyPa4Vrd4/Lx/MOZNFW7eeB4x9QDTYrATTFkX9Rpq2QwRZNJ9xl1ScnlJe+F2A7fsPkW97+A+ueYYn3yO/ezGJyUr5En8D+PsLTUyYrnvVTgKSxC96Y6H8t9+b8MXrp1X9zsBX4ys8CPH+/SfTFZ4W4FT+RmJtkhC2XZFkQei7nO/M1qcOFtPQWDAR0kWrhA9fQVFNdPUmd/TFwlyiKT4qEw/R4GwMtMlBARSHGrAYQsjiEpuw5kshVJhJdrWcbYvt0/F5CflrX/PkLG7ovRxvlTwTQSkJ+/fXNJMJImXFiJXaeOtSRVZvdfWrfJYa2099WVaq/3rgHf3czkUh4BN4gnCURbeK0tNI3IcJtF9N0hXTf+xNafrlmwBE3mGLHVebaUJFmQZ4nYrsFc8uyY97A9yKTJm8eq1rL3Wb5F2NWQtx+oNVshJ3hOWXMcaxJsdhtDbfTEOlukCqvGTVnE1dORXi7M4MtrubUlABUeuTMpIF7SPpYHH4a8=
  matrix:
    - GOPATH=$TRAVIS_BUILD_DIR/gosrc
install:
  - mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
  - mkdir -p "$TRAVIS_BUILD_DIR/static"
  - go get -v github.com/spf13/hugo
script: ./build.sh
after_success:
  - cd public
  - ls
  - git init
  - git config user.email "travis@example.com"
  - git config user.name "Travis ci"
  - git add .
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/halfdane/dsedley.git" master:gh-pages 2>&1 >/dev/null
