language: go
sudo: false

notifications:
  email:
    - halfdane@gmx.net

go:
  - 1.12

git:
  depth: 10

branches:
  only:
    - sources

install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install --tags extended
  - cd ${TRAVIS_BUILD_DIR}


script:
  - hugo
  
after_success:
- cd public
- git init
- git config user.email "travis@example.com"
- git config user.name "Travis ci"
- git add .
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push --force --quiet "https://${PUSH_TOKEN}@github.com/DavidSedley/DavidSedley.github.io.git" master:master 2>&1 >/dev/null
