sudo: false
branches:
  only:
  - sources
env:
  global:
  - GH_REF: github.com/DavidSedley/DavidSedley.github.io.git
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- mkdir -p "$TRAVIS_BUILD_DIR/static"
- go get -v github.com/spf13/hugo
- ${GOPATH}/bin/hugo version
cache:
  directories:
  - "${GOPATH}"
script: "${GOPATH}/bin/hugo"
after_success:
- cd public
- ls
- git init
- git config user.email "travis@example.com"
- git config user.name "Travis ci"
- git add .
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push --force --quiet "https://${PUSH_TOKEN}@github.com/DavidSedley/DavidSedley.github.io.git" master:master 2>&1 >/dev/null
