baseurl = "http://halfdane.github.io/dsedley/"
languageCode = "en-us"
# theme = "hyde"
theme = "bootie-docs"
uglyURLs = true

title = "David Sedley"


[params]
  themeColor = "theme-base-0a"
  description = "The quick brown fox jumps over the lazy dog"
  email = "dns1@cam.ac.uk"


[[menu.main]]
    name = "Curriculum Vitae"
    weight = 10
[[menu.main]]
    name = "Publications"
    weight = 20
[[menu.main]]
    name = "Other"
    weight = 100
[[menu.main]]
    name = "Website"
    weight = 1000
