baseurl = "http://halfdane.github.io/dsedley/"
languageCode = "en-us"
theme = "hyde"
uglyURLs = true

title = "David Sedley"


[params]
  themeColor = "theme-base-0a"
  description = "Human behavior flows from three main sources: desire, emotion, and knowledge. BANG"
  email = "dns1@cam.ac.uk"
