baseurl = "http://halfdane.github.io/dsedley/"
languageCode = "en-us"
theme = "hyde"
uglyURLs = true

title = "David Sedley"


[params]
  themeColor = "theme-base-0a"
  description = "nothing here"
  email = "dns1@cam.ac.uk"
